name: project_north
description: "Premium outdoor travel application for Norway."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^6.5.6
  firebase_core: ^4.12.1
  flutter_map: ^8.3.1
  geolocator: ^14.0.3
  google_fonts: ^6.3.2
  http: ^1.6.0
  hugeicons: ^1.1.7
  intl: any
  latlong2: ^0.10.1
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/project_north_welcome_logo.png
    - assets/images/welcome_camp_background.png
    - assets/images/project_north_splash.png
    - assets/images/project_north_app_icon.png
    - assets/images/villmark_icon_ios.png
    - assets/images/villmark_icon_android.png
    - assets/images/villmark_icon_android_foreground.png
    - assets/images/villmark_icon_android_monochrome.png

flutter_native_splash:
  color: "#0E2C1B"
  color_dark: "#0E2C1B"
  image: assets/images/villmark_icon_android_foreground.png

  android: true
  ios: true
  web: false

  android_gravity: center
  ios_content_mode: center

  android_12:
    color: "#0E2C1B"
    color_dark: "#0E2C1B"
    image: assets/images/villmark_icon_android_foreground.png
    icon_background_color: "#0E2C1B"
    icon_background_color_dark: "#0E2C1B"

flutter_launcher_icons:
  android: true
  ios: true

  image_path_android: assets/images/villmark_icon_android.png
  image_path_ios: assets/images/villmark_icon_ios.png

  adaptive_icon_background: "#0E2C1B"
  adaptive_icon_foreground: assets/images/villmark_icon_android_foreground.png
  adaptive_icon_monochrome: assets/images/villmark_icon_android_monochrome.png

  remove_alpha_ios: true