// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWzO9sh2Ee8uDilekuupcE3OXEgEv1MMc',
    appId: '1:178748326816:web:de1d606d164cb19bba1ac5',
    messagingSenderId: '178748326816',
    projectId: 'project-north-7096e',
    authDomain: 'project-north-7096e.firebaseapp.com',
    storageBucket: 'project-north-7096e.firebasestorage.app',
    measurementId: 'G-G35PBNZ9S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXuXojsASIQ5E3NE57HowPx_tphhYC1BY',
    appId: '1:178748326816:android:1a1ffa242fde595dba1ac5',
    messagingSenderId: '178748326816',
    projectId: 'project-north-7096e',
    storageBucket: 'project-north-7096e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQUAPxTOqfdRNWvkU-0QaNpD2q-ivsqAM',
    appId: '1:178748326816:ios:3d7e8ffb47202adeba1ac5',
    messagingSenderId: '178748326816',
    projectId: 'project-north-7096e',
    storageBucket: 'project-north-7096e.firebasestorage.app',
    iosBundleId: 'com.example.projectNorth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQUAPxTOqfdRNWvkU-0QaNpD2q-ivsqAM',
    appId: '1:178748326816:ios:3d7e8ffb47202adeba1ac5',
    messagingSenderId: '178748326816',
    projectId: 'project-north-7096e',
    storageBucket: 'project-north-7096e.firebasestorage.app',
    iosBundleId: 'com.example.projectNorth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWzO9sh2Ee8uDilekuupcE3OXEgEv1MMc',
    appId: '1:178748326816:web:ddc8b13e50eb1449ba1ac5',
    messagingSenderId: '178748326816',
    projectId: 'project-north-7096e',
    authDomain: 'project-north-7096e.firebaseapp.com',
    storageBucket: 'project-north-7096e.firebasestorage.app',
    measurementId: 'G-75E8X4D83E',
  );
}
